version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
    ignore:
      - dependency-name: gatsby
